#!/bin/sh

kill -TERM `pidof babysit_sofamatic.sh`
kill -TERM `pidof sofamatic.py`
kill -TERM `pidof sofa_display.py`
oled-exp -i -c write "Starting sofa.py..."
echo Starting sofa.py... > /var/run/sofa_status
/root/sofa/sofa_display.py >/dev/null &
/root/sofa/babysit_sofamatic.sh >/dev/null &
exit 0
