char *spinner[] = {
    "o                 ",
    " o                ",
    "  o               ",
    "   o              ",
    "    o             ",
    "     o            ",
    "      o           ",
    "       o          ",
    "        o         ",
    "         o        ",
    "          o       ",
    "           o      ",
    "            o     ",
    "             o    ",
    "              o   ",
    "               o  ",
    "                o ",
    "                 o",
    "                o ",
    "               o  ",
    "              o   ",
    "             o    ",
    "            o     ",
    "           o      ",
    "          o       ",
    "         o        ",
    "        o         ",
    "       o          ",
    "      o           ",
    "     o            ",
    "    o             ",
    "   o              ",
    "  o               ",
    " o                "
};

int spinner_len = 33;
int spinner_seq = 0;
